server:
  port: 8082

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  thymeleaf:
    cache: false
  # 나중에 DB 사용 시 아래 datasource 설정 주석 해제
  # datasource:
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   url: jdbc:mysql://localhost:3306/db_codingrecipe?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  #   username: user_codingrecipe
  #   password: 1234
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
